### ISSUE TITLE
Something about NewPortObject2

### ISSUE THREAD

**Issue by draveness** [magnuskiro/NTNU#1]
Sorry, I am not confused with the NewPortObject2 function in the CTMCP book, I search this on google, and find this repo, can you tell me how does the `Sin` work in this function.

```
fun {NewPortObject2 Proc}
   Sin in
   thread for Msg in Sin do {Proc Msg} end end
   {NewPort Sin}  
end
```

I find that in the previous section, the `NewPort` needs two argument, but there are just one, what does this means.. And When I create a port object in this way.

```
proc {ClientProc Msg}
   case Msg
   of work(Y) then Y1 Y2 in
      {Send Server calc(10.0 Y1)}
      {Wait Y1}
      {Send Server calc(20.0 Y2)}
      {Wait Y2}
      Y=Y1+Y2
   end
end 
Client={NewPortObject2 ClientProc}
```

And send message to the port objects, does this just append the `Sin` stream. I am really confused with this. And I don't find any community on CTMCP. Can you help me with this. Thanks so much.

**Comment by magnuskiro** [comment]
In the first code block we have fun(ction) {FunctionName arg1 arg2 arg3 etc}. So the functions take the name of the function as the first argument(ish).  Then we have a new 'Stream in'(I presume that is what the S stands for), followed by a thread with a for loop that handles all the messages in the stream. Fin the for loop all the messages in the stream is executed by the {Proc Msg} function/process. Last a its a function call to NewPort with Sin as argument. 

In the second code block a message handler is defined(first 10 lines), and then at the last line(Client={NewPortObject2 ClientProc}) it is used for all incoming messages in the previous code block.

For the Sin and PortObjects, you don't really send messages to the objects, it is rather the objects that read the messages in the 'in stream'(Sin). So the messages are sent to the stream called Sin.
I assume that this stream works as streams in other languages, and just appends the new incoming message to a que, or FIFO stack.

I hope this helps. 
Also, disclaimer: It's a long time since I took this subject, so I'm not 100% this is correct.

**Comment by draveness** [comment]
Thank you so much, does the first function `NewPortObject2` returns an function which take an port,  because in the previous section. `NewPort` takes two argument, stream and port.

**Comment by magnuskiro** [comment]
The NewPortObject2 function does not return anything. It takes it's name(NewPortObject2) as the first argument, and a reference to the message handling function(Proc) as the second argument.
The ´´´{NewPort Sin}´´´ line calls the 'NewPort' function with 'Sin' as the second argument(the name is the first arg).
